export const config = {
  name: "Payment Simulator",
  tag: "CONSISTENCY LAB",
  description: "Un pago, una identidad. Incluso cuando la respuesta se pierde.",
  post: "/api/payments",
  list: "/api/payments",
  sample: {
    amount: 125.5,
    currency: "PEN",
    scenario: "APPROVED",
  },
  columns: ["id", "status", "amount", "responseCode"],
  concepts: ["Idempotencia", "Concurrencia", "Reversos"],
  scenarios: ["APPROVED", "DECLINED", "LOST_RESPONSE"],
  repo: "payment-simulator",
  index: 2,
  secure: false,
  payment: true,
  monitor: false,
  brand: "mora",
  label: "PAGOS QUE PUEDES EXPLICAR",
  title: "Una intención.",
  emphasis: "Un solo pago.",
  intro:
    "Incluso cuando una respuesta se pierde. Explora pagos, consultas y reversos con una referencia que mantiene todo en orden.",
  accent: "#8b65d9",
  soft: "#f3eff9",
  kind: "payment",
  form: "Simula un pago",
  button: "Procesar pago",
  steps: ["Define el pago", "Conserva su referencia", "Consulta o revierte"],
  features: [
    [
      "01",
      "Una referencia, un pago",
      "Repite una solicitud con la misma clave y recupera el resultado.",
    ],
    [
      "02",
      "Respuestas claras",
      "Distingue una operación declinada de una respuesta perdida.",
    ],
    [
      "03",
      "Volver atrás",
      "Solicita un reverso sobre un pago aprobado y consulta su estado.",
    ],
  ],
};
